/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package suv1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author oschepkovau
 */

public class new_corr extends javax.swing.JFrame {
public static int id_mn;
public static int id_s ;
public static int id_fn;

    /**
     * Creates new form new_corr
     */
    public new_corr() {
        
        initComponents();
        init_form();
        ButtonGroup bg1 = new ButtonGroup();
        bg1.add(jRadioButton1);
        bg1.add(jRadioButton2);
        
        ButtonGroup bg2 = new ButtonGroup();
        bg2.add(jRadioButton3);
        bg2.add(jRadioButton4);
           
        if (id_mn !=0)
        {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void init_form()
    {
            
        Connection c;
        try {
            c = DriverManager.getConnection("jdbc:hsqldb:file:settings/testdb;shutdown=true", "ok","ghbdtl");
          //  PreparedStatement ps = null;
          //  ps = c.prepareStatement("select * from gr");
Statement s = c.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            
ResultSet rs = s.executeQuery("select * from gr");
rs.last();
String[] list_mod = new String[rs.getRow()];
//JOptionPane.showMessageDialog(rootPane, (list_mod.length), "Фамилия",JOptionPane.QUESTION_MESSAGE);
rs.beforeFirst();
while(rs.next()){
long id = rs.getLong("id_gr");
String firstName = rs.getString("group_w");
//JOptionPane.showMessageDialog(rootPane, (rs.getRow()-1), "Фамилия",JOptionPane.QUESTION_MESSAGE);
list_mod[rs.getRow()-1] = rs.getString("group_w");
System.err.println(firstName);
}    
jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(list_mod));

rs = s.executeQuery("select * from cat");
rs.last();
list_mod = new String[rs.getRow()];
//JOptionPane.showMessageDialog(rootPane, (list_mod.length), "Фамилия",JOptionPane.QUESTION_MESSAGE);
rs.beforeFirst();
while(rs.next()){
long id = rs.getLong("id_cat");
String firstName = rs.getString("categoty");
//JOptionPane.showMessageDialog(rootPane, (rs.getRow()-1), "Фамилия",JOptionPane.QUESTION_MESSAGE);
list_mod[rs.getRow()-1] = rs.getString("categoty");
System.err.println(firstName);
}    
jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(list_mod));

rs = s.executeQuery("select * from educat");
rs.last();
list_mod = new String[rs.getRow()];
//JOptionPane.showMessageDialog(rootPane, (list_mod.length), "Фамилия",JOptionPane.QUESTION_MESSAGE);
rs.beforeFirst();
while(rs.next()){
long id = rs.getLong("id_ed");
String firstName = rs.getString("education");
//JOptionPane.showMessageDialog(rootPane, (rs.getRow()-1), "Фамилия",JOptionPane.QUESTION_MESSAGE);
list_mod[rs.getRow()-1] = rs.getString("education");
System.err.println(firstName);
}    
jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(list_mod));


rs = s.executeQuery("SHUTDOWN");
c.close();


        } catch (SQLException ex) {
            Logger.getLogger(new_corr.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Новый сотрудник");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTabbedPane2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane2StateChanged(evt);
            }
        });

        jLabel1.setText("Группа");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Категория");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Образование");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextField1.setText("00.00.0000");

        jLabel4.setText("Дата рождения");

        jLabel5.setText("Пол");

        jRadioButton1.setText("Мужской");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("Женский");

        jTextField3.setText("---");

        jLabel8.setText("ФИО");

        jLabel10.setText("Начальный стаж/Дата поступления");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jComboBox3, javax.swing.GroupLayout.Alignment.LEADING, 0, 200, Short.MAX_VALUE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButton2)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(50, 50, 50))
        );

        jTabbedPane2.addTab("Основные данные", jPanel1);

        jRadioButton4.setText("Повышение квалификации");

        jLabel7.setText("Дата прохождения");

        jTextField2.setText("00.00.0000");

        jLabel6.setText("Переподготовка/Повышение квалификации");

        jRadioButton3.setText("Переподготовка");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Добавить");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Удалить");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton4)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton3))
                .addGap(24, 24, 24)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButton4)
                        .addComponent(jButton3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Переподготовка/Повышение квалификации", jPanel2);

        jButton2.setText("Сохранить");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(335, 335, 335))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
//    JOptionPane.showMessageDialog(rootPane, id_mn,"Переподготовка",
  //              JOptionPane.QUESTION_MESSAGE);
        //jRadioButton1.setFocusPainted(rootPaneCheckingEnabled);        // TODO add your handling code here:
        //jRadioButton2.setFocusPainted(false);
    }//GEN-LAST:event_jRadioButton1ActionPerformed
public void create_new_rec ()
{
         try {
            id_s = 0;
            if (jRadioButton1.isSelected())
            {
                id_s = 1;
            }
            else
            {
                id_s = 2;
            }
 
 String dt = this.jTextField1.getText();
 String ex = this.jTextField5.getText();
     
 
this.jTextField1.setText(dt.substring(0, 2) 
         + "/" + dt.substring(3, 5) 
         + "/" + dt.substring(6, 10));
              
 
this.jTextField5.setText(
           ex.substring(0, 2)   + "/"
         + ex.substring(3, 5)   + "/"
         + ex.substring(6, 8)   + "/"
         + ex.substring(9, 11)  + "/"
         + ex.substring(12, 14) + "/"
         + ex.substring(15, 19));
              
              
 
                      
Connection c = null;
c = DriverManager.getConnection("jdbc:hsqldb:file:settings/testdb;shutdown=true", "ok","ghbdtl");
Statement s = c.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
ResultSet rs = s.executeQuery("select max(id_fn) from full_name");
rs.first();
int id = rs.getInt(1);
JOptionPane.showMessageDialog(rootPane, id, "Фамилия",JOptionPane.QUESTION_MESSAGE);
rs = null;
rs = s.executeQuery("select max(id_mn) from sum_main");
rs.first();
int id_sum = rs.getInt(1);
JOptionPane.showMessageDialog(rootPane, (id_sum), "Фамилия",JOptionPane.QUESTION_MESSAGE);
String[] fn  =  this.jTextField3.getText().split(" ");
PreparedStatement ps = null;
ps = c.prepareStatement("insert into full_name "
        + "(id_fn,first_name,second_name,patronymic)"
        + " values(?,?,?,?)");
ps.setInt(1, id+1);ps.setString(2, fn[1]);ps.setString(3, fn[0]);
ps.setString(4, fn[2]);ps.execute();

///JOptionPane.showMessageDialog(rootPane, (jComboBox1.getSelectedIndex()), "Фамилия",JOptionPane.QUESTION_MESSAGE);
id_fn = 0;
id_fn = id+1;            
ps = c.prepareStatement("insert into sum_main "
+ "(id_mn,id_fn,id_gr,id_cat,id_ed,id_s,years_old,exp)"
+ " values(?,?,?,?,?,?,?,?)");

ps.setInt(1, id_sum + 1);
ps.setInt(2, id+1);
ps.setInt(3, jComboBox1.getSelectedIndex()+1);
ps.setInt(4, jComboBox2.getSelectedIndex()+1);
ps.setInt(5, jComboBox3.getSelectedIndex()+1);
ps.setInt(6, id_s);
ps.setString(7, this.jTextField1.getText());
ps.setString(8, this.jTextField5.getText());
ps.execute();
/**/
id_mn =0;
id_mn = id_sum+1;   
//rs = s.executeQuery("SHUTDOWN");

rs.close();
s.close();
c.close();
this.setTitle("Данные о новом сотруднике сохранены");
        } catch (SQLException ex) {
            Logger.getLogger(new_corr.class.getName()).log(Level.SEVERE, null, ex);
            
        }
}
public void set_rec()
{
       try {
            id_s = 0;
            if (jRadioButton1.isSelected())
            {
                id_s = 1;
            }
            else
            {
                id_s = 2;
            }
            
Connection c = null;
c = DriverManager.getConnection("jdbc:hsqldb:file:settings/testdb;shutdown=true", "ok","ghbdtl");
Statement s = c.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
String[] fn = this.jTextField3.getText().split(" ");
ResultSet rs = s.executeQuery("update full_name set "
        + "full_name.second_name = '" + fn[0] + "', "
        + "full_name.first_name = '" + fn[1] + "', "
        + "full_name.patronymic = '" + fn[2] + "' "
        + "where id_fn = " + this.id_fn);
rs = null;
 String dt = this.jTextField1.getText();
 String ex = this.jTextField5.getText();
     
 
this.jTextField1.setText(dt.substring(0, 2) 
         + "/" + dt.substring(3, 5) 
         + "/" + dt.substring(6, 10));
              
 
this.jTextField5.setText(
           ex.substring(0, 2)   + "/"
         + ex.substring(3, 5)   + "/"
         + ex.substring(6, 8)   + "/"
         + ex.substring(9, 11)  + "/"
         + ex.substring(12, 14) + "/"
         + ex.substring(15, 19));
//id_gr,id_cat,id_ed,id_s,years_old)"
///JOptionPane.showMessageDialog(rootPane, this.jTextField1.getText(),"Переподготовка",JOptionPane.QUESTION_MESSAGE);

rs = s.executeQuery("update sum_main set " 
        + "id_gr= " +  (this.jComboBox1.getSelectedIndex()+1) + ", "
        + "id_cat= " + (this.jComboBox2.getSelectedIndex()+1) + ", "
        + "id_ed= " + (this.jComboBox3.getSelectedIndex()+1) + ", "
        + "id_s= " + this.id_s + ", "
        + "years_old= '" + this.jTextField1.getText().toString() + "', "
        + "exp= '" + this.jTextField5.getText().toString() + "' "
        + "where id_mn = " + this.id_mn);

/*rs.last();
int id_sum = rs.getRow();
//JOptionPane.showMessageDialog(rootPane, (id_sum), "Фамилия",JOptionPane.QUESTION_MESSAGE);
String[] fn  =  this.jTextField3.getText().split(" ");
PreparedStatement ps = null;
ps = c.prepareStatement("insert into full_name "
        + "(id_fn,first_name,second_name,patronymic)"
        + " values(?,?,?,?)");
ps.setInt(1, id+1);ps.setString(2, fn[1]);ps.setString(3, fn[0]);
ps.setString(4, fn[2]);ps.execute();

JOptionPane.showMessageDialog(rootPane, (jComboBox1.getSelectedIndex()), "Фамилия",JOptionPane.QUESTION_MESSAGE);
            
ps = c.prepareStatement("insert into sum_main "
+ "(id_mn,id_fn,id_gr,id_cat,id_ed,id_s,years_old)"
+ " values(?,?,?,?,?,?,?)");

ps.setInt(1, id_sum + 1);
ps.setInt(2, id+1);
ps.setInt(3, jComboBox1.getSelectedIndex()+1);
ps.setInt(4, jComboBox3.getSelectedIndex()+1);
ps.setInt(5, jComboBox2.getSelectedIndex()+1);
ps.setInt(6, id_s);
ps.setString(7, this.jTextField1.getText());ps.execute();
/**/

rs = s.executeQuery("SHUTDOWN");

rs.close();
s.close();
c.close();
this.setTitle("Редактирование прошло успешно");

        } catch (SQLException ex) {
            Logger.getLogger(new_corr.class.getName()).log(Level.SEVERE, null, ex);
            
        }

}
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed



if (id_mn !=0 && this.jTextField3.getText().split(" ").length == 3 && this.jTextField1.getText().length() == 10 && this.jTextField5.getText().length() == 19)
{
this.set_rec();
}
else if (id_mn == 0 && this.jTextField3.getText().split(" ").length == 3 && this.jTextField1.getText().length() == 10 && this.jTextField5.getText().length() == 19)
{
this.create_new_rec();
}
else if (this.jTextField3.getText().split(" ").length !=3)
{
JOptionPane.showMessageDialog(rootPane,  "Ошибочное заполнение поля ФИО", "Ошибка заполнения",JOptionPane.QUESTION_MESSAGE);
}
else if (this.jTextField1.getText().length() !=10)
{
JOptionPane.showMessageDialog(rootPane,  "Ошибочное заполнение поля Дата рождения", "Ошибка заполнения",JOptionPane.QUESTION_MESSAGE);
}
else if (this.jTextField5.getText().length() !=19)
{
JOptionPane.showMessageDialog(rootPane,  "Ошибочное заполнение поля стаж ГГС", "Ошибка заполнения",JOptionPane.QUESTION_MESSAGE);
}

            /**/
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
            if (id_mn!=0)
            {
     
Connection c = null;
                try {
                    c = DriverManager.getConnection("jdbc:hsqldb:file:settings/testdb;shutdown=true", "ok","ghbdtl");
                    Statement s = c.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
ResultSet rs = s.executeQuery("select * from sum_main where id_mn = " + String.valueOf(id_mn));
rs.first();

this.jComboBox1.setSelectedIndex(rs.getInt("id_gr")-1);
this.jComboBox3.setSelectedIndex(rs.getInt("id_ed")-1);
this.jComboBox2.setSelectedIndex(rs.getInt("id_cat")-1);
this.jTextField1.setText(rs.getString("years_old"));
this.jTextField5.setText(rs.getString("exp"));

id_s = rs.getInt("id_s");
id_fn = rs.getInt("id_fn");
rs = null;
rs = s.executeQuery("select * from full_name where id_fn = " + String.valueOf(id_fn));
rs.first();

            
this.jTextField3.setText(rs.getString("second_name") + " " 
        + rs.getString("first_name") + " " 
        + rs.getString("patronymic"));
if (id_s ==1)
{
this.jRadioButton1.setSelected(true);
}
else if (id_s ==2)
{
this.jRadioButton2.setSelected(true);

}
rs = s.executeQuery("select * from retrain where id_fn = " + id_fn);
rs.last();
int count_ret = rs.getRow();
//JOptionPane.showMessageDialog(rootPane, count_ret,"Переподготовка",JOptionPane.QUESTION_MESSAGE);       
String test_q = "";//rs.getString(2);
System.err.println(test_q);

String[] headers = {"id","Переподготовка/Повышение квалификации", "Дата прохождения"};
Object[][] text_tab = new Object[rs.getRow()+40][3];
rs.beforeFirst();

test_q = "Переподготовка";
int ind_wh = rs.getRow()-1;
while(rs.next()) {
    text_tab[rs.getRow()-1][0] = rs.getLong("id_ret");
    text_tab[rs.getRow()-1][1] = test_q;
    text_tab[rs.getRow()-1][2] = rs.getString("time_ret");
ind_wh ++;
}
ind_wh = ind_wh +1;
test_q = "Повышение квалификации";
rs = null;
rs = s.executeQuery("select * from train where id_fn = " + id_fn);
rs.beforeFirst();
while(rs.next()) {
    text_tab[ind_wh][0] = rs.getLong("id_tra");
    text_tab[ind_wh][1] = test_q;
    text_tab[ind_wh][2] = rs.getString("time_tra");
ind_wh ++;
}
this.jTable1.setModel(new javax.swing.table.DefaultTableModel(
            text_tab,
           headers
        ));
c.close();

                } catch (SQLException ex) {
                    Logger.getLogger(new_corr.class.getName()).log(Level.SEVERE, null, ex);
                }

            


            }
            else if (id_mn==0)
            {
            this.jTextField1.setText("00/00/0000");
            this.jTextField5.setText("00/00/00/00/00/0000");
            }
            
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jRadioButton3.isSelected())
            {
               try {
                Connection c;
                PreparedStatement ps = null;
        c = DriverManager.getConnection("jdbc:hsqldb:file:settings/testdb;shutdown=true", "ok","ghbdtl");
Statement s = c.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
ResultSet rs = s.executeQuery("select max(id_ret)  from retrain");
rs.first();
int id_ret = rs.getInt(1);
//JOptionPane.showMessageDialog(rootPane, id_ret,"Переподготовка",JOptionPane.QUESTION_MESSAGE);       
     
ps = c.prepareStatement("insert into retrain "
+ "(id_ret,time_ret,id_fn)"
+ " values(?,?,?)");
ps.setInt(1, id_ret+1);ps.setInt(3,id_fn);
//JOptionPane.showMessageDialog(rootPane, id_fn,"Переподготовка",JOptionPane.QUESTION_MESSAGE);       
ps.setString(2, this.jTextField2.getText().toString());ps.execute();

/**/


c.close();
this.formWindowOpened(null);
} catch (SQLException ex) {
Logger.getLogger(new_corr.class.getName()).log(Level.SEVERE, null, ex);
}
}
            else if (jRadioButton4.isSelected())
            {
            try {
                 Connection c;
                PreparedStatement ps = null;
        c = DriverManager.getConnection("jdbc:hsqldb:file:settings/testdb;shutdown=true", "ok","ghbdtl");
Statement s = c.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
ResultSet rs = s.executeQuery("select max(id_tra)  from train");
rs.first();
int id_tra = rs.getInt(1);
///JOptionPane.showMessageDialog(rootPane, id_tra,"Квалификация",JOptionPane.QUESTION_MESSAGE);       
     
ps = c.prepareStatement("insert into train "
+ "(id_tra,time_tra,id_fn)"
+ " values(?,?,?)");
ps.setInt(1, id_tra+1);ps.setInt(3,id_fn);
ps.setString(2, this.jTextField2.getText().toString());ps.execute();

c.close();
this.formWindowOpened(null);
} catch (SQLException ex) {
Logger.getLogger(new_corr.class.getName()).log(Level.SEVERE, null, ex);
}
}
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
int id = Integer.valueOf(this.jTable1.getValueAt(this.jTable1.getSelectedRow(), 0).toString());
String te = this.jTable1.getValueAt(this.jTable1.getSelectedRow(), 1).toString();
//JOptionPane.showMessageDialog(rootPane, id,"Квалификация",JOptionPane.QUESTION_MESSAGE);       
Connection c;
    try {
        c = DriverManager.getConnection("jdbc:hsqldb:file:settings/testdb;shutdown=true", "ok","ghbdtl");
        PreparedStatement ps = null;
if (te.equals("Переподготовка"))
{
ps = c.prepareStatement("delete from retrain where id_ret = " + id);
ps.execute();
}
else if (te.equals("Повышение квалификации"))
{
ps = c.prepareStatement("delete from train where id_tra = " + id);
ps.execute();
}
c.close();
this.formWindowOpened(null);
    } catch (SQLException ex) {
        Logger.getLogger(new_corr.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTabbedPane2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane2StateChanged
this.setTitle("Редактирование");
    }//GEN-LAST:event_jTabbedPane2StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(new_corr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(new_corr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(new_corr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(new_corr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new new_corr().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
